name: pre-commit
on:
  pull_request:
    types:
      - opened
  push:
    branches: ['**']
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install package
        run: make init
      - name: Pre-commit run
        uses: pre-commit/action@v3.0.0
