name: unit-tests
on:
  pull_request:
    types:
      - opened
  push:
    branches: [ main ]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Format
        run: make test-unit
