name: unit-tests
on:
  pull_request:
    types:
      - opened
  push:
    branches: ['**']
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: unit test
        run: make test-unit
